import type { Metadata } from 'next'
import './globals.css'
import localFont from 'next/font/local'

const generalSansBold = localFont({ src: [ {
  path: '../../public/font/GeneralSansBold.otf',
  weight: '700',
  style: 'bold',
},
{
  path: '../../public/font/GeneralSansLight.otf',
  weight: '400',
  style: 'normal',
},
{
  path: '../../public/font/GeneralSansMedium.otf',
  weight: '500',
  style: 'medium',
},
{
  path: '../../public/font/GeneralSansSemibold.otf',
  weight: '600',
  style: 'semibold',
},
]})


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={generalSansBold.className}>{children}</body>
    </html>
  )
}
